spring:
  application:
    name: configdemo
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: main

build:
  version: 2.2.3
  name: "def-Build"
  type: "def Build"

management:
  endpoints:
    web:
      exposure:
        include: "*"