#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: product-service
#              uri: lb://product-service
#              predicates:
#                - Path=/api/products/**
#            - id: order-service
#              uri: lb://order-service
#              predicates:
#                - Path=/api/orders/**, /api/cart/**
#            - id: user-service
#              uri: lb://user-service
#              predicates:
#                - Path=/users/**
#              filters:
#                - RewritePath=/users(?<segment>/?.*), /api/users${segment}
#            - id: eureka-server
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/main
#              filters:
#                - SetPath=/
#            - id: eureka-server-static
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/**


server:
  port: 8080

#logging:
#  level:
#    root: INFO
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans

# Circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

# Security
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/ecom-app
          jwk-set-uri: http://keycloak:8080/realms/ecom-app/protocol/openid-connect/certs

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: gateway-service
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true