spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/productdb #or embarkx to use the db automatically created and assoc with the user
#    url: jdbc:postgresql://ep-square-dream-alw7hpv4-pooler.c-3.eu-central-1.aws.neon.tech/product?sslmode=require&channel_binding=require
#    url: jdbc:mysql://localhost:3306/productservice
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: PostgreSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database-platform: org.hibernate.dialect.MySQLDialect
    #have nice sql format in the console
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000
management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://zipkin:9411/api/v2/spans


app:
  message: "Hello user"

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: product-service
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
server:
  port: 8081

