build:
  id: 101
  version: 1.2.3
  name: "native Dev-Prod-Build AMAZING NEW CONFIG"
  type: "native Dev Build"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"