#spring:
#  application:
#    name: configdemo
#  profiles:
#    active: dev
#  config:
#    import: optional:configserver:http://localhost:8888
#  cloud:
#    config:
#      label: main

build:
  id: 001
  version: 0.2.3
  name: "native default Build"

management:
  endpoints:
    web:
      exposure:
        include: refresh